server.port=${PORT:8080}
server.address=0.0.0.0

razorpay.key=${RAZORPAY_API_KEY}
razorpay.secret=${RAZORPAY_API_SECRET}
razorpay.webhook.secret=${RAZORPAY_WEBHOOK_SECRET}
fast2sms.api.key=${FAST2SMS_API_KEY}
fast2sms.api.url=${FAST2SMS_API_URL}
gcp.bucket.name=dummy