spring.application.name=online
spring.datasource.url=${SPRING_DATASOURCE_URL} 
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
razorpay.key=${RAZORPAY_API_KEY:rzp_test_RtNLIrdQnUawTd}
razorpay.secret=${RAZORPAY_API_SECRET:xHvu5BOD4akCzIlEpz4N0KOI}
razorpay.webhook.secret=${RAZORPAY_WEBHOOK_SECRET:rakesh12}
fast2sms.api.key=mPoQL5j8kIgvpKcVbN0hZnsX7lUWMeBq4zEfCuYitwGDRAOSH9LBXa3mslVOAhxvwQuRqid08YJfbErZ
fast2sms.api.url=https://www.fast2sms.com/dev/bulkV2

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
